[package]
name = "vinland"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay = { git = "https://github.com/Smithay/smithay", features = [
    "backend_drm",
    "backend_winit",
    "backend_udev",
    "renderer_gl",
    "wayland_frontend",
    "xwayland",
    "desktop",
] }
calloop = "0.14"
tracing = "0.1"
tracing-subscriber = "0.3"
wayland-server = "0.31"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
notify = "7"
wayland-protocols-wlr = { version = "0.3", features = ["server"] }
xcursor = "0.3"
